//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.UserResponses = new HashSet<UserRespons>();
        }
    
        public int QuestionID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        [Required(ErrorMessage = "Question  is required")]
        public string QuestionText { get; set; }
        public string QuestionType { get; set; }
        public string OptionA { get; set; }
        public string OptionB { get; set; }
        public string OptionC { get; set; }
        public string OptionD { get; set; }
        public string CorrectAnswer { get; set; }
        public string ImageURL { get; set; }
        public byte[] OptionAImageData { get; set; }
        public byte[] OptionBImageData { get; set; }
        public byte[] OptionCImageData { get; set; }
        public byte[] OptionDImageData { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRespons> UserResponses { get; set; }
    }
}
